# Site settings
title: Leopoldo Pla
description: Lecturer, developer and researcher at the University of Alicante. Sometimes musician.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Leopoldo Pla Sempere
user_title: Lecturer & dev @ UAlicante. Sometimes musician.
email: (b64encoded) bGVvcG9sZG9wbGFzZW1wZXJlQGdtYWlsLmNvbQ==
twitter_username: pacofonix
github_username: lpla
instagram_username: poldet2
linkedin_username: leopoldoplasempere
stackoverflow_username: 153260
askubuntu_username: 153260
steam_username: leopoldops
youtube_username: Leopoldopla
thingiverse_username: lpla
oshpark_username: lpla

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
